# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Package Deploy

on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "edited"
      - "synchronize"
  push:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.0'
    - name: Install dependencies
      run: make
    - name: Build package
      run: make build
    - name: Publish package
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@5d1679fa6b895587c6eb10c3fe82205b440a580e
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}